<?php require_once '../views/inc/header.phtml'; ?>
<div class="card bg-light" style="width: 100%;max-width: 500px;margin: auto;">
    <div class="card-body">
        <h2>Recuperar contraseña</h2>

        <p class="text-justify">Si olvidó su contraseña simplemente ingrese su <span class="required">*</span>correo electrónico de identificación de inicio de sesión en el campo de entrada.</p>

        <?php if(isset($msg)): ?>

        <div class="alert alert-success" role="alert"><?= htmlspecialchars($success) ?></div>
        <p class="mt-4 text-justify"><?= htmlspecialchars($msg) ?></p>

        <?php else: ?>

        <p class="mt-4 text-justify"><span class="required">*</span>Su correo electrónico de identificación de inicio de sesión es la dirección de correo electrónico con la que se registró.</p>
        <div class="forgot_password_error error_box"></div>
        <form method="post" action="" name="forgot_password">
            <p><b>Recuperar contraseña </b>(si la ha olvidado)</p>
            <div class="form-group">
                <label for="email">Correo electrónico</label>
                <input type="email" name="email" id="email" class="form-control <?= empty($email_err) ? '' : 'invalid'; ?>" maxlength="50" value="<?= $email ?>">
                <div class="invalid-feedback"><?= htmlspecialchars($email_err); ?></div>
            </div>
            <div class="form-group">
                <a href="/login.php" style="color: unset;">¿Recuerdas tu contraseña?</a>
            </div>
            <button class="btn btn-lg btn-dark" type="submit">Recuperar contraseña</button>
        </form>

        <?php endif; ?>
    </div>
</div>
<?php require_once '../views/inc/footer.phtml'; ?>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        let login = new FormValidator('forgot_password', [
        {
            name: 'email',
            display: 'correo electrónico',
            rules: 'required|valid_email|max_length[50]'
        }], function(errors, evt) {
            let SELECTOR_ERRORS = document.querySelector('.forgot_password_error');
            if (errors.length > 0) {
                let errorString = '';
                let N = errors.length;
                for (let i = 0; i < N; i++) {
                    errorString += errors[i].message + '<br />';
                }
                errors[0].element.focus();
                SELECTOR_ERRORS.innerHTML = errorString;
                SELECTOR_ERRORS.style.display = 'block';
                window.scrollTo({top: 100, left: 100, behavior: 'smooth'});
                evt.preventDefault();
            } else {
                SELECTOR_ERRORS.style.display = 'none';
            }
        });
    });
</script>