<?php require_once '../views/inc/header.phtml'; ?>
<div class="" style="width: 100%;max-width: 500px;margin: auto;">
    <div class="card-body">
        <h2>Iniciar sesión</h2>
        <p class="text-justify">Si ya estás registrado simplemente ingrese su <span class="required">*</span>correo electrónico de identificación de inicio de sesión y contraseña en los campos de entrada, tenga en cuenta que su contraseña distingue entre mayúsculas y minúsculas.</p>
        <p class="mt-4 text-justify"><span class="required">*</span>Su correo electrónico de identificación de inicio de sesión es la dirección de correo electrónico con la que se registró.</p>
        
        <form method="post" action="" name="login">
            <p><b>Inicie sesión </b>(si ya está registrado) </p>
            <div class="form-group">
                <label for="email">Correo electrónico</label>
                <input type="email" name="email" id="email" class="form-control <?= empty($email_err) ? '' : 'invalid'; ?>" maxlength="50" value="<?= $email ?>" autofocus>
                <div class="invalid-feedback"><?= htmlspecialchars($email_err); ?></div>
            </div>
            <div class="form-group position-relative">
                <label for="password">Contraseña</label>
                <i class="material-icons visibility">visibility_off</i>
                <input type="password" name="password" id="password" class="form-control <?= empty($password_err) ? '' : 'invalid'; ?>" maxlength="50" style="padding-right: 50px;">
                <div class="invalid-feedback"><?= htmlspecialchars($password_err); ?></div>
            </div>
            <div class="form-group">
                <a href="/forgot_password.php" style="color: unset;">¿Olvidó su contraseña?</a>
            </div>
            <button class="btn btn-lg btn-block btn-dark" type="submit">Iniciar sesión</button>
        </form>
        <p class="mt-4">
            <a class="float-right" href="/register.php" style="color: unset;">¿Aún no tienes una cuenta?</a>
        </p>
    </div>
</div>
<?php require_once '../views/inc/footer.phtml'; ?>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        let login = new FormValidator('login', [
        {
            name: 'email',
            display: 'correo electrónico',
            rules: 'required|max_length[50]'
        }, {
            name: 'password',
            display: 'contraseña',
            rules: 'required'
        }], function(errors, evt) {
            if (errors.length > 0) {
                let N = errors.length;
                for (let i = 0; i < N; i++) {
                    errors[i].element.classList.add('invalid');
                    errors[i].element.nextElementSibling.innerHTML = errors[i].message;
                }
                errors[0].element.focus();
                evt.preventDefault();
            } else {
                disabledBtn();
            }
        });

        document.addEventListener('DOMContentLoaded', function() {
            checkInput();
        });

        let password = querySelector('#password');
        let visibilityToggle = querySelector('.visibility');


        password.onfocus = checkInput;
        password.oninput = checkInput;
        visibilityToggle.onclick = handleClick;

        function checkInput() {
            if (password.classList.contains('invalid')) {
                visibilityToggle.style.top = '38%';
            } else {
                visibilityToggle.style.top = '50%';
            }
            if (password.value.length > 0) {
                visibilityToggle.style.display = "block";
            } else {
                visibilityToggle.style.display = "none";
            }
        }

        function handleClick() {
            let type = password.getAttribute('type');
            let title;
            if (type === 'password') {
                type = 'text';
                visibilityToggle.textContent = 'visibility';
                title = 'Ocultar';
            } else {
                type = 'password';
                visibilityToggle.textContent = 'visibility_off';
                title = 'Mostrar';
            }
            visibilityToggle.setAttribute('title', title + ' contraseña');
            password.setAttribute('type', type);
        }
    });
</script>