<?php require_once '../views/inc/header.phtml'; ?>
<div class="card bg-light" style="width: 100%;max-width: 500px;margin: auto;">
    <div class="card-body">
        <h2>Iniciar sesión</h2>
        <p class="text-justify">Si ya estás registrado simplemente ingrese su <span class="required">*</span>correo electrónico de identificación de inicio de sesión y contraseña en los campos de entrada, tenga en cuenta que su contraseña distingue entre mayúsculas y minúsculas.</p>
        <p class="mt-4 text-justify"><span class="required">*</span>Su correo electrónico de identificación de inicio de sesión es la dirección de correo electrónico con la que se registró.</p>
        <div class="login_error error_box"></div>

        <!-- <div class="vertical-line"></div> -->
        
        <form method="post" action="" name="login">
            <p><b>Inicie sesión </b>(si ya está registrado)</p>
            <div class="form-group">
                <label for="email">Correo electrónico</label>
                <input type="email" name="email" id="email" class="form-control <?= empty($email_err) ? '' : 'invalid'; ?>" maxlength="50" value="<?= $email ?>">
                <div class="invalid-feedback"><?= htmlspecialchars($email_err); ?></div>
            </div>
            <div class="form-group position-relative">
                <i class="material-icons visibility">visibility_off</i>
                <label for="password">Contraseña</label>
                <a class="float-right" href="/forgot_password.php" style="color: unset;">¿Olvidó su contraseña?</a>
                <input type="password" name="password" id="password" class="form-control <?= empty($password_err) ? '' : 'invalid'; ?>" maxlength="50" style="padding-right: 50px;">
                <div class="invalid-feedback"><?= htmlspecialchars($password_err); ?></div>
            </div>
            <div class="form-group">
                <a href="/register.php" style="color: unset;">¿Aún no tienes una cuenta?</a>
            </div>
            <button class="btn btn-lg btn-dark" type="submit">Iniciar sesión</button>
        </form>
    </div>
</div>
<?php require_once '../views/inc/footer.phtml'; ?>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        let login = new FormValidator('login', [
        {
            name: 'email',
            display: 'correo electrónico',
            rules: 'required|max_length[50]'
        }, {
            name: 'password',
            display: 'contraseña',
            rules: 'required'
        }], function(errors, evt) {
            let SELECTOR_ERRORS = document.querySelector('.login_error');
            if (errors.length > 0) {
                let errorString = '';
                let N = errors.length;
                for (let i = 0; i < N; i++) {
                    errorString += errors[i].message + '<br />';
                }
                errors[0].element.focus();
                SELECTOR_ERRORS.innerHTML = errorString;
                SELECTOR_ERRORS.style.display = 'block';
                window.scrollTo({top: 100, left: 100, behavior: 'smooth'});
                evt.preventDefault();
            } else {
                SELECTOR_ERRORS.style.display = 'none';
            }
        });

        document.addEventListener('DOMContentLoaded', function() {
            checkInput();
        });

        let password = document.querySelector('#password');
        let visibilityToggle = document.querySelector('.visibility');

        if (password.classList.contains('invalid')) {
            visibilityToggle.style.top = '35%';
        }

        password.onfocus = checkInput;
        password.oninput = checkInput;
        visibilityToggle.onclick = handleClick;

        function checkInput() {
            if (password.value.length > 0) {
                visibilityToggle.style.display = "block";
            } else {
                visibilityToggle.style.display = "none";
            }
        }

        function handleClick() {
            let type = password.getAttribute('type');
            let title;
            if (type === 'password') {
                type = 'text';
                visibilityToggle.textContent = 'visibility';
                title = 'Ocultar';
            } else {
                type = 'password';
                visibilityToggle.textContent = 'visibility_off';
                title = 'Mostrar';
            }
            visibilityToggle.setAttribute('title', title + ' contraseña');
            password.setAttribute('type', type);
        }
    });
</script>