<?php require_once '../views/inc/header.phtml'; ?>
<div class="card bg-light" style="width: 100%;max-width: 500px;margin: auto;">
    <div class="card-body">
        <h2>Restablecer contraseña</h2>
        <p class="text-justify">Asegurese de crear una contraseña lo suficientemente fuerte y que pueda recordar con facilidad.</p>
        <form method="post" action="" name="reset_password">
            <p><b>Restablecer contraseña </b>(en caso de haberla olvidado)</p>
            <div class="form-group">
                <label for="password">Contraseña <span class="required">*</span></label>
                <small id="passwordHelpBlock" class="form-text text-muted mb-1 mt-0 text-justify">La contraseña debe tener al menos 8 caracteres de longitud y debe incluir al menos una letra mayúscula, un número y un carácter especial.</small>
                <input type="password" name="password" id="password" class="form-control <?= empty($password_err) ? '' : 'invalid'; ?>" maxlength="50" aria-describedby="passwordHelpBlock">
                <div class="invalid-feedback"><?= htmlspecialchars($password_err); ?></div>
            </div>
            <div class="form-group">
                <label for="password_confirm">Confirmar contraseña <span class="required">*</span></label>
                <input type="password" name="password_confirm" id="password_confirm" class="form-control <?= empty($password_confirm_err) ? '' : 'invalid'; ?>" maxlength="50">
                <div class="invalid-feedback"><?= htmlspecialchars($password_confirm_err); ?></div>
            </div>
            <input type="hidden" name="user_id" value="<?= $user_id ?>" readonly onmousedown="return false;">
            <input type="hidden" name="key" value="<?= $key ?>" readonly onmousedown="return false;">
            <button class="btn btn-lg btn-dark" type="submit">Restablecer contraseña</button>
        </form>
    </div>
</div>
<?php require_once '../views/inc/footer.phtml'; ?>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        let register = new FormValidator('reset_password', [
        {
            name: 'password',
            display: 'contraseña',
            rules: 'required|min_length[8]|max_length[50]'
        }, {
            name: 'password_confirm',
            display: 'confirmar contraseña',
            rules: 'required|matches[password]|max_length[50]'
        }], function(errors, evt) {
            if (errors.length > 0) {
                let N = errors.length;
                for (let i = 0; i < N; i++) {
                    errors[i].element.classList.add('invalid');
                    errors[i].element.nextElementSibling.innerHTML = errors[i].message;
                }
                errors[0].element.focus();
                evt.preventDefault();
            } else {
                disabledBtn();
            }
        });
    });
</script>