        </main>
        <!-- <section style="width: 100%;max-width: 520px;margin: auto;">
            <form id="form">
                <div class="input-group input-group-lg">
                    <input id="task" type="text" class="form-control" onblur="this.value = this.value.trim();" aria-describedby="taskHelpBlock" maxlength="50" placeholder="Ingrese su correo electrónico">
                    <div class="input-group-append">
                        <button id="submit" type="submit" class="btn btn-dark rounded-right">Suscribirse</button>
                    </div>
                    <div class="invalid-feedback">Utiliza un formato que coincida con el solicitado.</div>
                </div>
            </form>
        </section> -->
        <footer>
        	<div class="container text-center p-4 small">
        	    <p class="">&copy; <?= 2017 . '-' . date('Y') ?> | Desarrollado por JYS | All rights reserved.</p>
        	    <p class="mb-0">Unos de estos días me organizaré.</p>
        	</div>
        </footer>
        <button class="btn btn-danger rounded-circle scrolltotop"><i class="material-icons" style="vertical-align: middle;">arrow_upward</i></button>

        <script src="/js/main.js"></script>
        <script src="/js/theme.js"></script>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <script src="/js/validate.min.js"></script>
        <noscript>Deberías activar javaScript para ver la totalidad del contenido.</noscript>

        <script>
            document.addEventListener('DOMContentLoaded', () => {
                let scrollToTop = querySelector('.scrolltotop');

                scrollToTop.onclick = () => {
                    alert('En construcción!');
                }
            });
        </script>
    </body>
</html>