<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top p-3">
    <div class="container">
        <a class="navbar-brand mb-1" href="/index.php">App <i class="material-icons ml-2" style="vertical-align: middle;">stars</i></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/index.php">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about.php">Acerca de</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <?php if (isset( $_SESSION['user_id'] )): ?>
                <li class="nav-item"><a class="nav-link" href="/dashboard.php">Dashboard</a></li>
                <li class="nav-item"><a class="nav-link" href="/logout.php" onclick="return confirm('¿Deseas cerrar la sesión?');">Salir</a></li>
                <?php else: ?>
                <li class="nav-item"><a class="nav-link" href="/login.php">Iniciar sesión</a></li>
                <li class="nav-item"><a class="nav-link" href="/register.php">Registrarse</a></li>
                <?php endif; ?>
            </ul>
            <!-- <form class="form-inline my-2 my-lg-0">
              <a class="btn btn-lg btn-dark my-2 my-sm-0" href="/register.php">Registrarse</a>
            </form> -->
        </div>
    </div>
</nav>
<style>
    .navbar-brand::before {
        content: "\01F988  ";
    }
</style>