<nav class="navbar navbar-expand-md navbar-light p-3">
    <div class="container">
        <a class="navbar-brand mb-1" href="/index.php">App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/index.php">Inicio <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about.php">Acerca de</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <?php if (isset( $_SESSION['user_id'] )): ?>
                <li class="nav-item"><a class="nav-link" href="/dashboard.php">Dashboard</a></li>
                <li class="nav-item"><a class="nav-link" href="/logout.php" onclick="return confirm('¿Deseas cerrar la sesión?');">Salir</a></li>
                <?php else: ?>
                <li class="nav-item"><a class="nav-link" href="/login.php">Iniciar sesión</a></li>
                <li class="nav-item"><a class="nav-link" href="/register.php">Registrarse</a></li>
                <?php endif; ?>
                <li class="nav-item">
                    <button class="nav-link dark-switcher" aria-label="Toggle Dark Mode." title="Toggle Dark Mode">
                        <img src="img/moon.svg" class="theme-icon" alt="Dark Mode">
                        <!-- <img src="img/sun.svg" class="theme-icon light-mode" alt="Light Mode" style="display: none;"> -->
                    </button>
                </li>
            </ul>
        </div>
    </div>
</nav>
<style>
    .navbar-brand::before {
        content: "\01F988  ";
    }
</style>