<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="/favicon.ico" rel="icon">
        <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">
        <style>

            .jumbotron {
                background-color: inherit;
            }

        </style>
        <title>404</title>
    </head>
    <body>
        <div class="container">
            <div class="jumbotron">
                <h1 class="display-6">404</h1>
                <p class="lead">Not Found</p>
                <hr class="my-4">
                <a href="https://developer.mozilla.org/es/docs/Web/HTTP/Status/404">https://developer.mozilla.org/es/docs/Web/HTTP/Status/404</a>
            </div>
        </div>
    </body>
</html>