<?php require_once '../views/inc/header.phtml'; ?>
<section class="">
	<h1 class="mb-4">App</h1>
	<p class="text-justify" style="">App es una aplicación desarrollada con PHP, muestra las operaciones comunes que realiza un usuario para registrarse, activar su cuenta, iniciar sesión, recuperar y cambiar su contraseña.</p>
	<p>version: <strong><i class="material-icons mr-2">build </i><?= htmlspecialchars(APP_VERSION); ?></strong></p>
</section>
<?php require_once '../views/inc/footer.phtml'; ?>